//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DZSchool_DIPLOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classes
    {
        public int id { get; set; }
        public Nullable<int> Pupil { get; set; }
        public Nullable<int> Timetable { get; set; }
        public int idteacher { get; set; }
    
        public virtual Pupil Pupil1 { get; set; }
        public virtual Teachers Teachers { get; set; }
        public virtual TimeTable TimeTable1 { get; set; }
    }
}
