//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DZSchool_DIPLOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pupil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pupil()
        {
            this.Classes = new HashSet<Classes>();
        }
    
        public int id { get; set; }
        public Nullable<int> idMarks { get; set; }
        public Nullable<double> AvgMarks { get; set; }
        public string Fio { get; set; }
        public Nullable<int> idInf { get; set; }
        public string FatherFio { get; set; }
        public string MotherFio { get; set; }
        public string ContactNumber { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Classes> Classes { get; set; }
        public virtual MarksOfStudent MarksOfStudent { get; set; }
        public virtual PupilInfo PupilInfo { get; set; }
    }
}
