//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DZSchool_DIPLOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TimeTable()
        {
            this.Classes = new HashSet<Classes>();
        }
    
        public int id { get; set; }
        public Nullable<int> idSubject { get; set; }
        public string Class { get; set; }
        public string Classroom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Classes> Classes { get; set; }
        public virtual subjects subjects { get; set; }

        public string SubjectType
        {
            get
            {
                return subjects.NameOfSubject;
            }
        }

        //public string TeaherName
        //{
        //    get
        //    {
        //        return Teachers.Fio;
        //    }
        //}
        //public virtual Teachers Teachers { get; set; }
    }
}
